package org.lemon.advent.year2024

import org.lemon.advent._
import org.lemon.advent.year2024.Day08._

class Day08Test extends UnitTest:

  test("part 1 example") {
    val in = """|............
                |........0...
                |.....0......
                |.......0....
                |....0.......
                |......A.....
                |............
                |............
                |........A...
                |.........A..
                |............
                |............""".stripMargin
    part1(in) shouldBe 14
  }

  test("part 1") {
    part1(read(file(2024)(8))) shouldBe 222
  }

  test("part 2 example") {
    val in = """|............
                |........0...
                |.....0......
                |.......0....
                |....0.......
                |......A.....
                |............
                |............
                |........A...
                |.........A..
                |............
                |............""".stripMargin
    part2(in) shouldBe 34
  }

  test("part 2") {
    part2(read(file(2024)(8))) shouldBe 884
  }
