name: Launch Scala Steward
on:
  workflow_dispatch:
  schedule:
  - cron: '22 17 15 11 *' # XXXX-11-15T17:22
jobs:
  scala-steward:
    runs-on: ubuntu-latest
    steps:
    - uses: scala-steward-org/scala-steward-action@v2
      with:
        github-app-id: ${{ secrets.APP_ID }}
        github-app-installation-id: ${{ secrets.APP_INSTALLATION_ID }}
        github-app-key: ${{ secrets.APP_PRIVATE_KEY }}
